#metadata
address = 'mailto:kathrin.heim@zhbluzern.ch'
collection = 'ZHB E-Codices'
collection_id = 'zhb_ecodices'
ingest_workflow = 'W01'
keywords = '[E-Codices, ZHB, Sondersammlung]'
last_changed = '2023-07-27'
organisation = 'Zentral- und Hochschulbibliothek Luzern'
organisation_id = 'zhb'
sets = '[ecodices, zhb, sosa]'
signature = 'zhb_'
